name: quiz_go
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5
  dio: ^5.3.2
  go_router: ^10.0.0
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/100.otf
          weight: 100
        - asset: assets/fonts/300.otf
          weight: 300
        - asset: assets/fonts/400.ttf
          weight: 400
        - asset: assets/fonts/500.ttf
          weight: 500
        - asset: assets/fonts/700.otf
          weight: 700
        - asset: assets/fonts/900.ttf
          weight: 900