export './authentication/auth_widgets/mobile_view.dart';
export './authentication/auth_widgets/web_view.dart';
export './home/home_page.dart';
export './quiz/option_widget.dart';
export './quiz/question_page.dart';
export './quiz/quiz_page.dart';
export './quiz/score_page.dart';
export 'authentication/login.dart';
export 'authentication/sign_up.dart';
