// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7b4EIKyqaZfUCR7b08L9Dy42H_E7G1xc',
    appId: '1:871229306315:web:ffa05d82e1b16f5c24724e',
    messagingSenderId: '871229306315',
    projectId: 'quizgo-c9064',
    authDomain: 'quizgo-c9064.firebaseapp.com',
    storageBucket: 'quizgo-c9064.appspot.com',
    measurementId: 'G-V1Y21ZJDNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqUe0wQr2nZb94WPSF0Utj2ydI3RGd7i8',
    appId: '1:871229306315:android:90e24ca286ecdf3924724e',
    messagingSenderId: '871229306315',
    projectId: 'quizgo-c9064',
    storageBucket: 'quizgo-c9064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBxF5R9dLfQZ862Li3H0nDfzW4cvk0h0',
    appId: '1:871229306315:ios:3bed59834bc3cbac24724e',
    messagingSenderId: '871229306315',
    projectId: 'quizgo-c9064',
    storageBucket: 'quizgo-c9064.appspot.com',
    iosClientId: '871229306315-oe19ouselsgi627cjf6fj8dhob7qdf6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizGo',
  );
}
